[main]
term = xterm-256color
font = DejaVu Sans Mono:size=9
# font = Hack:size=9
dpi-aware = no  # auto/yes causes large cut font
pad = 2x2
underline-offset = 1px
initial-window-size-chars = 209x70
app-id = foot
title = foot
selection-target = primary

letter-spacing=1px
line-height=15px
word-delimiters=│`|"'()[]{}<>

# important: make bold text using a brighter color using our defined secondary colors
bold-text-in-bright=palette-based

[environment]
LANG = de_DE.UTF-8
LC_ALL = de_DE.UTF-8

[bell]
urgent = no
notify = no
visual = no

[scrollback]
lines = 16384
multiplier = 3.0
indicator-position = relative

[url]
launch = firefox ${url}
osc8-underline = always
# protocols = http,https,file

[cursor]
style = block
style = beam
blink = no
blink-rate = 1000
blink = yes
# color unset -> default (inverse)

[mouse]
hide-when-typing = yes
alternate-scroll-mode = yes

#[colors]
[colors-dark]
foreground = 65B22A
# background = 282828
background = 000000
bold = FFFFFF

# ! black
regular0 = 000000
bright0 = 21680D
dim0 = 000000
# ! red
regular1 = B21818
bright1 = FF5454
dim1 = B21818
# ! green
regular2 = 18B218
bright2 = 54FF54
dim2 = 18B218
# ! yellow
regular3 = B26818
bright3 = FFFF54
dim3 = B26818
# ! blue
regular4 = 1818B2
bright4 = 5454FF
dim4 = 1818B2
# ! magenta
regular5 = B218B2
bright5 = FF54FF
dim5 = B218B2
# ! cyan
regular6 = 18B2B2
bright6 = 54FFFF
dim6 = 18B2B2
# ! white
regular7 = B2B2B2
bright7 = FFFFFF
dim7 = FFFFFF

alpha = 1 # 0.95

# selection-foreground
# selection-background

jump-labels = 000000 B26818
scrollback-indicator = 000000 5454FF
search-box-no-match = 000000 B21818
search-box-match = 000000 B26818
urls = B26818

[colors-light]
# solarized-light
foreground=657b83
background=fdf6e3
bold=586e75

cursor=fdf6e3 586e75
background=fdf6e3
foreground=657b83
regular0=eee8d5
regular1=dc322f
regular2=859900
regular3=b58900
regular4=268bd2
regular5=d33682
regular6=2aa198
regular7=073642
bright0=cb4b16
bright1=fdf6e3
bright2=93a1a1
bright3=839496
bright4=657b83
bright5=6c71c4
bright6=586e75
bright7=002b36

jump-labels = fdf6e3 cb4b16
scrollback-indicator = fdf6e3 268bd2
search-box-no-match = fdf6e3 dc322f
search-box-match = fdf6e3 cb4b16
urls = eee8d5

# [colors-gnome]
# foreground=ffffff
# background=000000
#
# regular0=000000
# regular1=cc0000
# regular2=4e9a06
# regular3=c4a000
# regular4=3465a4
# regular5=75507b
# regular6=06989a
# regular7=d3d7cf
#
# bright0=555753
# bright1=ef2929
# bright2=8ae234
# bright3=fce94f
# bright4=729fcf
# bright5=ad7fa8
# bright6=34e2e2
# bright7=eeeeec

[csd]
preferred = server
size = 26
color = ff000000
font = DejaVu Sans Mono
hide-when-maximized = no
border-width = 0
border-color = ff000000
button-width = 26
button-color = ff000000
button-minimize-color = ff000000
button-maximize-color = ff000000
button-close-color = ff000000

[key-bindings]
clipboard-copy = Control+Shift+c XF86Copy
clipboard-paste = Control+Shift+v XF86Paste
primary-paste = Shift+Insert

color-theme-toggle = Control+Shift+F10
prompt-prev = Control+Shift+z
prompt-next = Control+Shift+x

scrollback-up-page = Shift+Page_Up
scrollback-down-page = Shift+Page_Down

pipe-command-output = ["wl-copy", "--primary"] Shift+End

pipe-selected = ["/home/fbest/.config/foot/keyboard-select.sh"] Mod1+Escape Mod1+s

font-increase = Control+plus Control+equal Control+KP_Add
font-decrease = Control+minus Control+KP_Subtract
font-reset = Control+0 Control+KP_0
spawn-terminal = Control+Shift+n
unicode-input = none

[search-bindings]
cancel = Control+g Control+c Escape
commit = Return
find-prev = Control+r
find-next = Control+s
cursor-left = Left Control+b
cursor-right = Right Control+f
